### ISSUE TITLE
This is the kinda thing

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [FKLC/Torrent-To-Google-Drive-Downloader#15]
That will basically ruin colab for everyone actually trying to learn/experiment with machine learning. Love that you take a GPU just cause you needed more space lol. Whatever though, I guess this is what it is.

**Comment by FKLC** [comment]
You are right, at first I used this notebook to download this [machine learning course](http://academictorrents.com/details/e8b1f9c5bf555fe58bc73addb83457dd6da69630) which is actually small sized and without copyright issues but than it turns out to be people are using to download illegal torrents then downloading from drive which is not the purpose of this notebook.

I was actually about to delete it but when I checked project after a while I saw people forked and starred for a reason I didn't know about. (you can see this [paragraph as a proof](https://github.com/FKLC/Torrent-To-Google-Drive-Downloader/blob/6ec89382f048e3622552eec2a13259f43bd909ec/README.md#this-notebook-is-completely-useless))

But now it became unstoppable there is 21 forks even if i delete the repo they will stay. But thanks for your attention as your request I'll archive repo and add a note about it is against Google Colab's policy
