### ISSUE TITLE
Team Drive?

### ISSUE THREAD

**Issue by r27dev** [FKLC/Torrent-To-Google-Drive-Downloader#4]
Is it possibile to download torrent to a Team Drive instead of the main Drive?

**Comment by FKLC** [comment]
I have never used Team Drive but according to this [stackoverflow question](https://stackoverflow.com/q/53111395/7957705) you should be able to use by changing save path to
```python
params = {"save_path": "/content/drive/Team Drives/AndSoOn.../"}
```
if that doesn't work (it won't probably because of [this](https://gsuiteupdates.googleblog.com/2019/04/shared-drives.html)) maybe you can try:
```python
params = {"save_path": "/content/drive/Shared drives/AndSoOn.../"}
```

**Comment by FKLC** [comment]
Closing issue because of 15 days of inactivity.
